<a href="https://colab.research.google.com/github/opeyemiferanmi1/Pre-Bootcamp_Tutorials/blob/master/L4N_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
train  = pd.read_csv('/content/drive/My Drive/competition/Train.csv')
test = pd.read_csv('/content/drive/My Drive/competition/Test.csv')
subfile = pd.read_csv('/content/drive/My Drive/competition/SampleSubmission.csv')

 ### Handling missing values

In [ ]:
train.isna().sum().any()

True

In [ ]:
train

Applicant_ID  form_field1  ...  form_field50  default_status
0      Apcnt_1000000       3436.0  ...      0.044335              no
1      Apcnt_1000004       3456.0  ...      0.322436              no
2      Apcnt_1000008       3276.0  ...      0.011640             yes
3      Apcnt_1000012       3372.0  ...      0.082729              no
4      Apcnt_1000016       3370.0  ...      0.045630              no
...              ...          ...  ...           ...             ...
55995   Apcnt_999968       3740.0  ...      0.241598              no
55996   Apcnt_999972       3360.0  ...           NaN             yes
55997   Apcnt_999980       3500.0  ...      0.163153              no
55998   Apcnt_999988       3280.0  ...      0.002997              no
55999   Apcnt_999996       3522.0  ...      0.678245              no

[56000 rows x 52 columns]

In [ ]:
train_dr=train.copy()
test_new=test.copy()

In [ ]:
#def fill_median(data):
 # for i in data.columns:
  #  data = data.fillna(data[i].median(), axis=1)
  #return data

In [ ]:
#train_dr[col_for_median] = fill_median(train_dr[col_for_median])
#test_dr[col_for_median] = fill_median(test_dr[col_for_median])

In [ ]:
#def fill_mean(data):
 # for i in data.columns:
  #  data = data.fillna(data[i].mean(), axis=1)
  #return data

In [ ]:
#train_dr[col_for_mean] = fill_mean(train_dr[col_for_mean])
#test_dr[col_for_mean] = fill_mean(test_dr[col_for_mean])

In [ ]:
train_dr.fillna(-999, inplace=True)
test_new.fillna(-999, inplace=True)

In [ ]:
train_dr.isna().sum().any()

False

In [ ]:
test_new.isna().sum().any()

False











































































































































































































































































































































































































































































































































































































































































































































































































### Handling Categorical Variables

In [ ]:
#maping target
train_dr.default_status.replace({'yes':1,'no':0, }, inplace=True)

In [ ]:
#train_dr['form_field47'] = pd.get_dummies(train_dr['form_field47'])
#test_new['form_field47'] = pd.get_dummies(test_new['form_field47'])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train_dr['form_field47']=le.fit_transform(train_dr['form_field47'])
test_new['form_field47']=le.fit_transform(test_new['form_field47'])

### Model

In [ ]:
test_new

Applicant_ID  form_field1  ...  form_field49  form_field50
0      Apcnt_1000032       3236.0  ...      0.000000      0.011221
1      Apcnt_1000048       3284.0  ...      0.504974      0.043525
2      Apcnt_1000052       -999.0  ...      0.000000   -999.000000
3      Apcnt_1000076       3232.0  ...      0.788809      0.104029
4      Apcnt_1000080       3466.0  ...      1.637733      0.163124
...              ...          ...  ...           ...           ...
23995   Apcnt_999940       3258.0  ...      0.000000   -999.000000
23996   Apcnt_999956       3514.0  ...      3.000000      0.930931
23997   Apcnt_999976       3302.0  ...      4.855060   -999.000000
23998   Apcnt_999984       3334.0  ...      0.818733      0.023749
23999   Apcnt_999992       3324.0  ...      0.000000      0.391927

[24000 rows x 51 columns]

In [ ]:
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()
#train_dr['Rank_by_Income_label']=le.fit_transform(train_dr['Rank_by_Income_label'])
#train_dr['Rank_by_Credit Worthiness_label']=le.fit_transform(train_dr['Rank_by_Credit Worthiness_label'])

#test_dr['Rank_by_Income_label']=le.fit_transform(test_dr['Rank_by_Income_label'])
#test_dr['Rank_by_Credit Worthiness_label']=le.fit_transform(test_dr['Rank_by_Credit Worthiness_label'])

In [ ]:
features = train_dr.columns.drop(['Applicant_ID', 'default_status'])
X = train_dr[features]
y = train_dr.default_status
test_new = test_new.drop('Applicant_ID',1)

In [ ]:
X

form_field1  form_field2  ...  form_field49  form_field50
0           3436.0      0.28505  ...      1.129518      0.044335
1           3456.0      0.67400  ...      1.620483      0.322436
2           3276.0      0.53845  ...      1.513370      0.011640
3           3372.0      0.17005  ...      0.664452      0.082729
4           3370.0      0.77270  ...      1.427891      0.045630
...            ...          ...  ...           ...           ...
55995       3740.0      0.01730  ...      0.000000      0.241598
55996       3360.0      2.01145  ...      0.000000   -999.000000
55997       3500.0      0.76640  ...      2.000000      0.163153
55998       3280.0      0.05235  ...      0.000000      0.002997
55999       3522.0      0.46930  ...      3.000000      0.678245

[56000 rows x 50 columns]

In [ ]:
!pip install catboost

     |████████████████████████████████| 66.1MB 63kB/s 


In [ ]:
from sklearn.metrics import roc_auc_score
def model_auc(model):
    train_auc = roc_auc_score(ytrain, model.predict_proba(xtrain)[:, 1])
    val_auc = roc_auc_score(yval, model.predict_proba(xval)[:, 1])
    print(f'Train AUC: {train_auc}, Val Auc: {val_auc}')

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xval, ytrain, yval = train_test_split(X, y, random_state=42, test_size=0.2, stratify=y)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=700)
clf.fit(xtrain,ytrain)
y_pred = clf.predict(xval)
model_auc(clf)#83660

Train AUC: 0.9999998167910051, Val Auc: 0.8371402869208047


In [ ]:
pip install rgf_python

     |████████████████████████████████| 768kB 8.2MB/s 


In [ ]:
from rgf.sklearn import RGFClassifier
rgf = RGFClassifier(l2= 0.1, max_leaf= 1000, min_samples_leaf= 5)
rgf.fit(xtrain,ytrain)
y_pred =rgf.predict(xval)
model_auc(rgf)#84345

Train AUC: 0.8495118285869918, Val Auc: 0.8434523971948591


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = {'max_leaf':[100,200,300,400,500,600,700,800,900,1000],
              'l2':[0.1,0.2,0.3],
              'min_samples_leaf':[5,10]}
clf = GridSearchCV(estimator=rgf,
                   param_grid=parameters,
                   scoring='roc_auc',
                   n_jobs = -1,
                   cv = 3)
clf.fit(X, y)
print(clf.best_params_)
#clf.cv_results

In [ ]:
import xgboost as xgb
xgb_model = xgb.XGBClassifier(objective="binary:logistic", random_state=42)
xgb_model.fit(xtrain, ytrain)
 
y_pred = xgb_model.predict(xval)
 
#print(confusion_matrix(yval, y_pred))
model_auc(xgb_model)#837

Train AUC: 0.8453473291749634, Val Auc: 0.8379899886845813


In [ ]:
#cat3
from catboost import CatBoostClassifier, Pool, cv
clas = CatBoostClassifier(eval_metric='AUC',verbose=False)
clas.fit(xtrain,ytrain,eval_set=(xval,yval))
y_pred =clas.predict(xval)
model_auc(clas)#84528

Train AUC: 0.8804104660660084, Val Auc: 0.8451258497071521


In [ ]:
#cat1
from catboost import CatBoostClassifier, Pool, cv
classifier = CatBoostClassifier(iterations=1000,use_best_model=True, random_seed=42,depth=6, learning_rate=0.03,l2_leaf_reg = 7,eval_metric='AUC',verbose=False)
classifier.fit(xtrain,ytrain,eval_set=(xval,yval))
y_pred =classifier.predict(xval)
model_auc(classifier)#84607638

Train AUC: 0.8766308375612581, Val Auc: 0.8460904342876541


In [ ]:
cat = CatBoostClassifier(thread_count =-1,rsm = 0.98,eval_metric='AUC',verbose=False)
cat.fit(xtrain,ytrain,eval_set=(xval,yval))
y_pred =cat.predict(xval)
model_auc(cat)

Train AUC: 0.8815586314477766, Val Auc: 0.8450217007821215


In [ ]:
# Model with default hyperparameters
import lightgbm as lgb
model_lgb = lgb.LGBMClassifier()#1360,5
model_lgb

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
model_lgb.fit(xtrain,ytrain,eval_set=(xval,yval))
y_pred =model_lgb.predict(xval)
model_auc(model_lgb)

[1]	valid_0's binary_logloss: 0.534569
[2]	valid_0's binary_logloss: 0.516805
[3]	valid_0's binary_logloss: 0.502438
[4]	valid_0's binary_logloss: 0.490491
[5]	valid_0's binary_logloss: 0.480197
[6]	valid_0's binary_logloss: 0.47176
[7]	valid_0's binary_logloss: 0.464598
[8]	valid_0's binary_logloss: 0.458505
[9]	valid_0's binary_logloss: 0.452923
[10]	valid_0's binary_logloss: 0.448144
[11]	valid_0's binary_logloss: 0.443785
[12]	valid_0's binary_logloss: 0.440186
[13]	valid_0's binary_logloss: 0.436561
[14]	valid_0's binary_logloss: 0.433589
[15]	valid_0's binary_logloss: 0.430923
[16]	valid_0's binary_logloss: 0.428538
[17]	valid_0's binary_logloss: 0.42631
[18]	valid_0's binary_logloss: 0.424412
[19]	valid_0's binary_logloss: 0.422591
[20]	valid_0's binary_logloss: 0.421133
[21]	valid_0's binary_logloss: 0.419619
[22]	valid_0's binary_logloss: 0.418376
[23]	valid_0's binary_logloss: 0.417336
[24]	valid_0's binary_logloss: 0.416352
[25]	valid_0's binary_logloss: 0.41548
[26]	valid_0

In [ ]:
lgb2 = lgb.LGBMClassifier(colsample_bytree = 0.53188948770158, learning_rate = 0.1,
                          max_depth= 21, min_child_samples = 313, min_child_weight= 0.01,
                          num_leaves = 25, reg_alpha=2, reg_lambda = 0,
                          subsample = 0.9373388595945467,verbose =2)
lgb2.fit(xtrain,ytrain,eval_set=(xval,yval))
y_pred =lgb2.predict(xval)
model_auc(lgb2)

[1]	valid_0's binary_logloss: 0.53679
[2]	valid_0's binary_logloss: 0.520553
[3]	valid_0's binary_logloss: 0.506095
[4]	valid_0's binary_logloss: 0.494607
[5]	valid_0's binary_logloss: 0.48546
[6]	valid_0's binary_logloss: 0.475756
[7]	valid_0's binary_logloss: 0.468761
[8]	valid_0's binary_logloss: 0.462965
[9]	valid_0's binary_logloss: 0.457672
[10]	valid_0's binary_logloss: 0.451913
[11]	valid_0's binary_logloss: 0.446873
[12]	valid_0's binary_logloss: 0.443052
[13]	valid_0's binary_logloss: 0.439717
[14]	valid_0's binary_logloss: 0.436966
[15]	valid_0's binary_logloss: 0.433699
[16]	valid_0's binary_logloss: 0.430998
[17]	valid_0's binary_logloss: 0.428366
[18]	valid_0's binary_logloss: 0.426612
[19]	valid_0's binary_logloss: 0.424803
[20]	valid_0's binary_logloss: 0.422848
[21]	valid_0's binary_logloss: 0.421597
[22]	valid_0's binary_logloss: 0.419996
[23]	valid_0's binary_logloss: 0.418622
[24]	valid_0's binary_logloss: 0.417511
[25]	valid_0's binary_logloss: 0.416352
[26]	valid_

In [ ]:
#THIS TOO
#from sklearn.ensemble import RandomForestClassifier
#from catboost import Pool, CatBoostClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import MinMaxScaler 
from sklearn.pipeline import Pipeline
import lightgbm as lgb
from sklearn.ensemble import RandomForestClassifier
from catboost import CatBoostClassifier, Pool, cv
from rgf.sklearn import RGFClassifier
from sklearn.ensemble import VotingClassifier
strKfold = StratifiedKFold(n_splits=25,shuffle=True)
#import lightgbm as lgb
cat1 = CatBoostClassifier(depth=6,iterations=1000, learning_rate=0.03,l2_leaf_reg = 7,eval_metric='AUC', random_seed=42,verbose = False)#846
#cat2 = CatBoostClassifier(thread_count =-1,rsm = 0.98,eval_metric='AUC',verbose=False)#43
cat3 = CatBoostClassifier(eval_metric='AUC',verbose=False)#845
#lgb1 = lgb.LGBMClassifier(n_jobs =-1,verbose =0,learning_rate=0.01,n_estimators=1360,max_depth=5)
lgb2 = lgb.LGBMClassifier(colsample_bytree = 0.53188948770158,verbose=2, learning_rate = 0.1,
                          max_depth= 21, min_child_samples = 313, min_child_weight= 0.01,
                          num_leaves = 25, reg_alpha=2, reg_lambda = 0,
                          subsample = 0.9373388595945467)#8443
from rgf.sklearn import RGFClassifier
rgf = RGFClassifier(l2= 0.1, max_leaf= 1000, min_samples_leaf= 5)
#rgf = RGFClassifier(l2= 0.1, max_leaf= 1000, min_samples_leaf= 5)#8442
rf = RandomForestClassifier(n_estimators = 700,max_features = 'sqrt', max_depth = 8, criterion ='gini', random_state=42)

In [ ]:
#This one
 
scores = []
preds = []
#catboost_model1 = CatBoostClassifier(eval_metric='AUC', random_seed=12345,verbose = False)
model = VotingClassifier(estimators=[('CatBoost1', cat1),('CatBoost3', cat3),('LGB',lgb2),('RFC',rf)], voting='soft',weights=[3,2,1,1])
i = 1
for train, val in strKfold.split(X,y):
    pipe = Pipeline([('scaler', MinMaxScaler()), ('model', model)])
    xtrain, xval, ytrain, yval = X.iloc[train], X.iloc[val], y.iloc[train], y.iloc[val]
    #cat_features = cate_features_index
    pipe.fit(xtrain, ytrain)
    result = model_auc(pipe)
    score = roc_auc_score (yval, pipe.predict_proba(xval)[:, 1])
    pred = pipe.predict_proba(test_new)[:,1]
    scores.append(score)
    preds.append(pred)
    i += 1
 
test_pred = np.mean(scores)
pred_result = np.mean(preds)

Train AUC: 0.8864081186506495, Val Auc: 0.8376872271401701
Train AUC: 0.885340351054559, Val Auc: 0.8542971648461631
Train AUC: 0.8871599764597909, Val Auc: 0.8303739366016117
Train AUC: 0.8858780113637381, Val Auc: 0.8404104329519767
Train AUC: 0.885235287897401, Val Auc: 0.8547781746648031
Train AUC: 0.8863905597916, Val Auc: 0.8333063708995531
Train AUC: 0.8861434897126818, Val Auc: 0.8522490983762143
Train AUC: 0.8863328933927052, Val Auc: 0.83537061482977
Train AUC: 0.8866358562105949, Val Auc: 0.8297883125399044
Train AUC: 0.8861584853712093, Val Auc: 0.8433881641386689
Train AUC: 0.8858918851201238, Val Auc: 0.8532033405180539
Train AUC: 0.8859715879077216, Val Auc: 0.8445245858552565
Train AUC: 0.8863376298545664, Val Auc: 0.8303716557926404
Train AUC: 0.8860454605181713, Val Auc: 0.8490637781289351
Train AUC: 0.8865621085141758, Val Auc: 0.8274266743792003
Train AUC: 0.8860280635389918, Val Auc: 0.8467090856015832
Train AUC: 0.8853304611390964, Val Auc: 0.848622138633869
Train

In [ ]:
test_pred #The validation score is smaller than what ive been getting but performed better on the leaderboard with just 0.00001

0.8411687511135264

In [ ]:
#pred_result = np.mean(preds)
pred_result

0.2442743608889611

#### Randomsearchcv for RandomForest Classifier

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
params = { 
    'n_estimators': [500, 700],
    'max_features': ['auto', 'sqrt'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}
print(params)

{'n_estimators': [500, 700], 'max_features': ['auto', 'sqrt'], 'max_depth': [4, 5, 6, 7, 8], 'criterion': ['gini', 'entropy']}


In [ ]:
clf = RandomForestClassifier()
clf_random = RandomizedSearchCV(estimator = clf, param_distributions = params, 
                                scoring='roc_auc', n_iter = 100, 
                                cv = StratifiedKFold(n_splits=5),
                                verbose=True, random_state=42, n_jobs = -1)
clf_random.fit(X, y)
print(clf_random.best_params_)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 40 is smaller than n_iter=100. Running 40 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed: 20.8min
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed: 130.4min
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed: 134.7min finished


{'n_estimators': 700, 'max_features': 'sqrt', 'max_depth': 8, 'criterion': 'gini'}


In [ ]:
print(clf_random.best_params_)

{'n_estimators': 700, 'max_features': 'sqrt', 'max_depth': 8, 'criterion': 'gini'}


In [ ]:
pred =pipe.predict_proba(test_new)[:,1]

In [ ]:
preds

[array([0.34461847, 0.34292811, 0.39493341, ..., 0.26842386, 0.51673263,
        0.19094721]),
 array([0.29253251, 0.3762812 , 0.38977933, ..., 0.2693293 , 0.53780837,
        0.18625255]),
 array([0.35066852, 0.3606203 , 0.41574289, ..., 0.263477  , 0.56801933,
        0.19622924]),
 array([0.3341257 , 0.3422303 , 0.40239132, ..., 0.26577432, 0.51452673,
        0.20825566]),
 array([0.35150011, 0.38512082, 0.39924903, ..., 0.27519099, 0.50295509,
        0.17339796]),
 array([0.32395384, 0.3023858 , 0.37071038, ..., 0.26530823, 0.5134894 ,
        0.15381936]),
 array([0.28467692, 0.30055631, 0.40355402, ..., 0.27450709, 0.49659056,
        0.19929029]),
 array([0.30722467, 0.37665058, 0.40214775, ..., 0.2678992 , 0.50995747,
        0.18880077]),
 array([0.33288831, 0.31321573, 0.40391145, ..., 0.27554122, 0.51168472,
        0.19029506]),
 array([0.30013751, 0.30924402, 0.40941183, ..., 0.28567476, 0.53315132,
        0.18507732]),
 array([0.33947672, 0.35214902, 0.38055201, ..., 0

In [ ]:
test_id = test.Applicant_ID

In [ ]:
submission = pd.DataFrame({'Applicant_ID' : test_id, 'default_status' : pred}).to_csv("starter-submission.csv", index = False)

In [ ]:
 from google.colab import files
files.download("starter-submission.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>